### ISSUE TITLE
hackthiscontract.io not working

### ISSUE THREAD

**Issue by zzh1996** [pdaian/hackthiscontract#8]
When I click the deploy button, it always shows "Your contract is compiled and processing! Please wait!"

**Comment by relyt29** [comment]
Seems like the geth node needed an update. Thanks for the notification.

Should work now.

**Comment by zzh1996** [comment]
It's down again

**Comment by relyt29** [comment]
Yeah I took it down, server costs.

We'll spin it up again in a while but for now we're not going to host it. 

Are you actively using it?

**Comment by zzh1996** [comment]
> Yeah I took it down, server costs.
> 
> We'll spin it up again in a while but for now we're not going to host it.
> 
> Are you actively using it?

No but I'm recommending hackthiscontract.io to my friends :)
I think smart contract hacking games can be written as a DApp, which doesn't require server code, and can be hosted on github pages

**Comment by relyt29** [comment]
Yes there are some competitors that I'm aware of: 

https://ethernaut.openzeppelin.com/

https://capturetheether.com/
